### ISSUE TITLE
subscribe with user login

### ISSUE THREAD

**Issue by barmanrajdeep** [gs-akhan/salesforce-debugger#2]
v1

**Comment by barmanrajdeep** [comment]
We add this and depricate subscribe using org ID

**Comment by gs-akhan** [comment]
@barmanrajdeep @gs-skumar 
Added support for User Name . And depricated the orgId .

Please enter user name and test this out .. 

Thanks.

**Comment by gs-rbarman** [comment]
:) wonderful man!!!
